name: Build and Lint

on: ['push', 'pull_request']

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci --include=dev
        working-directory: ${{ env.working-directory }}

      - name: Build and lint
        run: |
          npm run build
          npm run lint
        working-directory: ${{ env.working-directory }}
