name: release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci --include=dev
        working-directory: ${{ env.working-directory }}
      - run: npm publish --access=public
        working-directory: ${{ env.working-directory }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
